### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by eedrah** [peterheesterman/about-me#1]
Welcome back to github :) I'm guessing a new job is using github much more than EndGame was? And it says you are now based in Auckland? I hope it's going well for you.

P.S. This seems fun: https://github.com/peterheesterman/ipper

**Comment by peterheesterman** [comment]
🥇 I didn't see this until now - i am really not that attentive. 🥇  

Yeah, a new job - a large change. `Github` for all the things, `javascript` for all the things too!

I forgot about `ipper`. Gonna hit you up on Linkedin. 👀
